### ISSUE TITLE
Clarification on Line 401 in apt.py: Meaning of 'optimized' and its relation to 'perturbed'

### ISSUE THREAD

**Issue by Chenguoz** [TreeLLi/APT#6]
Thank you for sharing your work and code! I have a question regarding the following line in the `apt.py`file:
```
elif self.cfg.AT.PROMPT == 'optimized':
```
Could you clarify the meaning of `'optimized'` in this context? Specifically:

Does `'optimized'` correspond to `'perturbed'` as described in the paper?
I noticed that when the hyperparameter APT is set to either `'perturbed'` or `'onfly'`, the same code seems to be executed. 

Could you confirm if this behavior is intended, or if there are differences that I may have missed?

I appreciate your time and help in understanding this part of the code better. Looking forward to your response!

Best regards

**Comment by TreeLLi** [comment]
Hi @Chenguoz,

thanks for your interest in our work. The `optimized` is the `perturbed`. `optimized` was used throughout our development. When releasing the code, we intended to replace `optimized` with `perturbed` to align with the naming in the paper but we forget to update there. This should not affect the results reported in the paper and your running of `onfly` and `constant`. We are sorry for this mistake and will fix it soon. Thank you again for helping us find this bug. Please let me know if something still unclear.

Kind regards,
Lin

**Comment by Chenguoz** [comment]
Thanks for your quick response!
